/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalGdprRouteImport } from './routes/legal.gdpr'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalDataRetentionRouteImport } from './routes/legal.data-retention'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalChildrenPrivacyRouteImport } from './routes/legal.children-privacy'
import { Route as LegalCcpaRouteImport } from './routes/legal.ccpa'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalGdprRoute = LegalGdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDataRetentionRoute = LegalDataRetentionRouteImport.update({
  id: '/data-retention',
  path: '/data-retention',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalChildrenPrivacyRoute = LegalChildrenPrivacyRouteImport.update({
  id: '/children-privacy',
  path: '/children-privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCcpaRoute = LegalCcpaRouteImport.update({
  id: '/ccpa',
  path: '/ccpa',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/ccpa': typeof LegalCcpaRoute
  '/legal/children-privacy': typeof LegalChildrenPrivacyRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/data-retention': typeof LegalDataRetentionRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/ccpa': typeof LegalCcpaRoute
  '/legal/children-privacy': typeof LegalChildrenPrivacyRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/data-retention': typeof LegalDataRetentionRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/ccpa': typeof LegalCcpaRoute
  '/legal/children-privacy': typeof LegalChildrenPrivacyRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/data-retention': typeof LegalDataRetentionRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
    | '/sitemap.xml'
    | '/legal/acceptable-use'
    | '/legal/ccpa'
    | '/legal/children-privacy'
    | '/legal/cookies'
    | '/legal/data-retention'
    | '/legal/disclaimer'
    | '/legal/gdpr'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
    | '/sitemap.xml'
    | '/legal/acceptable-use'
    | '/legal/ccpa'
    | '/legal/children-privacy'
    | '/legal/cookies'
    | '/legal/data-retention'
    | '/legal/disclaimer'
    | '/legal/gdpr'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
    | '/sitemap.xml'
    | '/legal/acceptable-use'
    | '/legal/ccpa'
    | '/legal/children-privacy'
    | '/legal/cookies'
    | '/legal/data-retention'
    | '/legal/disclaimer'
    | '/legal/gdpr'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LegalRoute: typeof LegalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/gdpr': {
      id: '/legal/gdpr'
      path: '/gdpr'
      fullPath: '/legal/gdpr'
      preLoaderRoute: typeof LegalGdprRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/data-retention': {
      id: '/legal/data-retention'
      path: '/data-retention'
      fullPath: '/legal/data-retention'
      preLoaderRoute: typeof LegalDataRetentionRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/children-privacy': {
      id: '/legal/children-privacy'
      path: '/children-privacy'
      fullPath: '/legal/children-privacy'
      preLoaderRoute: typeof LegalChildrenPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/ccpa': {
      id: '/legal/ccpa'
      path: '/ccpa'
      fullPath: '/legal/ccpa'
      preLoaderRoute: typeof LegalCcpaRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalCcpaRoute: typeof LegalCcpaRoute
  LegalChildrenPrivacyRoute: typeof LegalChildrenPrivacyRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDataRetentionRoute: typeof LegalDataRetentionRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalGdprRoute: typeof LegalGdprRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalCcpaRoute: LegalCcpaRoute,
  LegalChildrenPrivacyRoute: LegalChildrenPrivacyRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDataRetentionRoute: LegalDataRetentionRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalGdprRoute: LegalGdprRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LegalRoute: LegalRouteWithChildren,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
